name: 'OpenCommit Action'

on:
  workflow_run:
    workflows: ["unit-tests.yml"] # This should be the file name of the first workflow
    branches: [main]
    types: 
      - completed

jobs:
  opencommit:
    timeout-minutes: 10
    name: OpenCommit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: di-sukharev/opencommit@github-action-v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          OCO_OPENAI_API_KEY: ${{ secrets.OCO_OPENAI_API_KEY }}
          OCO_EMOJI: true
          OCO_MODEL: gpt-4-turbo-preview
