name: Unit Tests and Update README

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests-and-update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests and generate test results
      run: npm run test:json

    - name: Update README.md
      run: npm run updateReadme

    - name: Commit and push if README.md changed
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add README.md
        git commit -m "Update README.md with latest test results" -a || echo "No changes to commit"
        git push
